### ISSUE TITLE
希望可以支持不同小程序打包

### ISSUE THREAD

**Issue by xkloveme** [4chao/preset#2]
需不需要我提交相关代码?

**Comment by xkloveme** [comment]
uView UI vue3bug有点多,我劝直接用uni-ui吧,兼容性会高一点

**Comment by PentaTea** [comment]
抱歉回复晚了

1.这个项目始于自用, 并没有考虑其他平台打包, 再加上我没太多精力去维护所有平台的可用性测试, 所以目前无适配其他平台的计划
2.当然欢迎你的pr, 个人认为不应该在package.json中罗列所有的平台,可以写一个脚本用来让用户自己选择要添加的平台, 或是直接用一个脚本代理`yarn dev`命令并接收一个平台选项
3.确实bug太多了,我会考虑更换其他组件库

**Comment by PentaTea** [comment]
ui库已换成uniui
